id: P010446
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:50:19.217829
source_metadata:
  id: bdr:W1KG14749
  title: གཅུང་པོ་དོན་ཡོད་དང་དོན་གྲུབ་ཀྱི་རྣམ་ཐར།
  author: ''
  volumes:
    539764cced214de5b424411907a868ee:
      image_group_id: I2PD18171
      title: ''
      volume_number: 1
      total_pages: 196
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
