id: I17D3ACCD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T12:56:11+00:00'
last_modified: '2022-06-08T13:40:02.938141+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14749
  title: གཅུང་པོ་དོན་ཡོད་དང་དོན་གྲུབ་ཀྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    50C8:
      image_group_id: I2PD18171
      title: ''
      total_pages: 196
      order: 1
      base_file: 50C8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
